services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VITE_APP_PORT}:80"
    env_file:
      - .env

networks:
  default:
    network.name: react
    external: true
